In [16]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\it services\\IT Services\\customers-10000.csv")

In [3]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,26-08-2020,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,27-04-2020,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/

In [4]:
df.tail(7)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9993,9994,5B8Ffc59EeBd87D,Bernard,Wolf,Huynh-Best,Port Barryborough,Bhutan,977.287.5016x4827,337-342-2622x707,rmorse@lane.com,29-04-2021,http://www.sweeney.com/
9994,9995,D7E40cCBde64d59,Kim,Yoder,Carpenter-Fleming,Lake Lawrenceview,Armenia,667.966.2755x2648,001-662-149-5921x60026,jefferypatrick@taylor.com,04-03-2022,https://butler-gibbs.com/
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [5]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [6]:
df.shape

(10000, 12)

In [7]:
df = pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\it services\\IT Services\\customers-10000.csv")

In [8]:
df_csv= pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\it services\\IT Services\\customers-10000.csv",skiprows=3)

In [9]:
df_csv.head()

,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
0,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
1,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
2,6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,-5361,briangriffin@chang.org,13-08-2021,https://www.roberts.com/
3,7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,09-04-2020,http://www.holt.com/
4,8,47C5cEE243c9A7b,Glenn,Wiggins,Glenn-Harvey,Ambershire,Falkland Islands (Malvinas),245-207-5608x563,8806867785,changkellie@howell.com,02-04-2021,http://carlson.com/

In [18]:
import pandas as pd

In [20]:
excel=pd.read_excel("C:\\Users\\Admin\\OneDrive\\Desktop\\it services\\IT Services\\IT_Services_Task_Sheet.xlsx", sheet_name='Sheet1')

In [21]:
df_csv.head()

,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
0,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
1,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
2,6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,-5361,briangriffin@chang.org,13-08-2021,https://www.roberts.com/
3,7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,09-04-2020,http://www.holt.com/
4,8,47C5cEE243c9A7b,Glenn,Wiggins,Glenn-Harvey,Ambershire,Falkland Islands (Malvinas),245-207-5608x563,8806867785,changkellie@howell.com,02-04-2021,http://carlson.com/

In [22]:
#display last 6 sell
df.tail(6)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9994,9995,D7E40cCBde64d59,Kim,Yoder,Carpenter-Fleming,Lake Lawrenceview,Armenia,667.966.2755x2648,001-662-149-5921x60026,jefferypatrick@taylor.com,04-03-2022,https://butler-gibbs.com/
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [23]:
# Display random 7 sample rows
df.sample(7)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
5591,5592,87bFb2e9d6d0A3d,Laura,Swanson,Glenn-Parrish,Shortmouth,Mexico,222.879.3008,001-668-633-1870x3253,mackkerri@mclaughlin-taylor.biz,24-03-2022,https://www.boone.com/
6012,6013,eD30cdb4C0cac13,Latoya,Olson,"Long, Odonnell and Zavala",Lake Loretta,Congo,313-376-7621x8994,134.526.0827x7896,bruce08@parrish.info,01-06-2021,https://www.mcdaniel.com/
7107,7108,91f00bF306FfAfA,Johnathan,Acevedo,Richardson PLC,New Cindy,Guam,8550090400,001-829-148-2793x9233,chandlerbeth@madden.info,24-06-2020,http://www.ortiz.info/
1285,1286,12f9Ee9f736Ae49,Julie,Bean,Haney and Sons,Mckinneyberg,Honduras,(439)698-5476,(735)410-3198,tyrone18@walton.com,23-02-2022,https://vincent.biz/
466,467,ee24eBb8cb1CeC8,Alisha,Brooks,Costa-Burton,Mataborough,Vanuatu,-9418,760-158-8625x32259,djarvis@gonzales.org,12-04-2021,http://gutierrez.com/
4957,4958,cdf15BD9318F5bf,Cynthia,Mckee,Peck LLC,North Kristina,Ghana,136-599-2523,(329)539-9119x632,kbarton@schaefer-dorsey.org,06-11-2021,https://www.gonzales-clarke.com/
9907,9908,9E6Ee7D48AADDD6,Candace,Santana,Blankenship Inc,Patriciastad,Armenia,(405)641-3019x725,001-729-743-2304x4779,bstark@lawson.com,18-01-2022,https://kline-patel.com/

In [26]:
#display first 4 rows of Briana , Napal and East Jardan column
df[['Index','Company']].head(4)

   Index                   Company
0      1              Mosley-David
1      2  Horn, Shepard and Watson
2      3               Irwin-Oneal
3      4          Richardson Group

In [27]:
#display last 10 rows of Briana , Nepal ,East Jordan column
df[['Website','Subscription Date','Email']].head(4)

,Website,Subscription Date,Email
0,http://www.escobar.org/,26-08-2020,urangel@espinoza-francis.net
1,https://tyler-pugh.info/,27-04-2020,xreese@hall-donovan.com
2,https://www.mack-bell.net/,22-03-2022,haleybraun@blevins-sexton.com
3,https://delacruz-freeman.org/,02-07-2020,hohailey@anthony.com

In [28]:
# for display 2nd to 6th rows
df[2:7]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
5,6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,-5361,briangriffin@chang.org,13-08-2021,https://www.roberts.com/
6,7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,09-04-2020,http://www.holt.com/

In [29]:
# for display starting to 10 th 
df[:11]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,26-08-2020,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,27-04-2020,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
5,6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,-5361,briangriffin@chang.org,13-08-2021,https://www.roberts.com/
6,7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,09-04-2020,http://www.holt.com/
7,8,47C5cEE243c9A7b,Glenn,Wiggins,Glenn-Harvey,Ambershire,Falkland Islands (Malvinas),245-207-5608x563,8806867785,changkellie@howell.com,02-04-2021,http://carlson.com/
8,9,cacaD68a5e4BF4b,Bruce,Payne,"Arroyo, Cain and Hudson",Barrettview,Zimbabwe,391.313.4649x42910,166.227.5055,mayerjerome@hurst-graham.net,26-11-2020,https://www.glenn-snow.com/
9,10,436b9c41cfb1fa3,Brendan,Franco,"Schaefer, Blair and Shaffer",New Rickey,Ukraine,001-315-224-3556,254-621-7128x7573,kentryan@stone-oneill.com,29-06-2021,http://ruiz.com/
10,11,9653ca648e2E414,Martin,Hawkins,Lopez Inc,Lake Bobton,Mauritania,001-402-567-1320,732-908-7945,danielbuckley@hatfield.info,02-05-2021,https://www.newman.com/

In [30]:
# for display last 2 rows
df[-2:]

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [31]:
# create new df_col dataframe from df.copy() method
df_col=df.copy()

In [32]:
df_col

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,26-08-2020,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,27-04-2020,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [33]:
df.drop(columns=['Phone 1'], inplace=True)
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,915.112.1727,urangel@espinoza-francis.net,26-08-2020,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,(209)172-7124x3651,xreese@hall-donovan.com,27-04-2020,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,(567)135-1918,haleybraun@blevins-sexton.com,22-03-2022,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,196-189-7767x770,hohailey@anthony.com,02-07-2020,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,552.051.2979x342,alvaradojesse@rangel-shields.com,17-01-2021,https://welch.info/
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-349-692-1755x055,nicolasandrade@bates.info,27-04-2022,http://thomas-ramos.com/
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,001-295-324-5502x5411,tracy68@wade.com,17-01-2022,https://www.campbell.com/
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,13-01-2022,http://www.george-scott.com/
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,14-04-2020,https://www.payne.info/
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,423.632.2539x98740,ngallagher@martinez.com,27-06-2020,http://nixon.net/

In [36]:
df_col.loc[df_col["Phone 1"] == 9087675544, "Phone 1"] = 7788996654
df_col.loc[df_col["Phone 1"] == 9966332211, "Phone 2"] = 77441123

In [35]:
print(df_col.columns)

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')